services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - "./data:/var/lib/mysql" #./data 내경로 /var/lib/mysql(리눅스 안의 mysql 경로) 
    environment:
      MYSQL_ROOT_PASSWORD: password
    command:
      - --character-set-server=utf8mb4 #이모티콘 저장
      - --collation-server=utf8mb4_unicode_ci #뭔지 모름
